/* Personajes de una clase, D&D 5e 2014. Datos de fuentes en class-data.js. */
(function(root){'use strict';
const D=root.ClassData,R=()=>root.Rules;
const id=s=>s.classId||'bard',info=s=>D.classes[id(s)],sub=s=>D.subclasses.find(x=>x.id===s.classSubclass)||(id(s)==='bard'&&s.subclass==='eloquence'?D.subclasses.find(x=>x.id==='bard-college-of-eloquence'):null);
const at=(arr,l)=>arr?.[l-1]||0,mod=n=>Math.floor((n-10)/2),clone=x=>JSON.parse(JSON.stringify(x));
function casting(s){const c=info(s),sc=sub(s),caster=sc?.caster||c.caster,ability=s.castingAbility||sc?.ability||c.ability||'int';let type=c.prepared?'prepared':'known';if(id(s)==='wizard')type='book';if(!caster||caster==='1/2'&&s.level<2||caster==='1/3'&&s.level<3)type='none';return {caster,ability,type,cantrips:at(sc?.cantrips||c.cantrips,s.level)+((s.classChoices?.['Pact Boon']||[]).includes('pact-of-the-tome-PHB')?3:0),known:at(sc?.known||c.known,s.level)};}
function slots(s){const c=casting(s).caster,l=s.level,t=R().slots;if(c==='full')return t[l];if(c==='pact'){const level=Math.min(5,Math.ceil(l/2)),a=Array(level).fill(0);a[level-1]=l===1?1:l<11?2:l<17?3:4;return a;}if(c==='1/2')return l<2?[]:t[Math.ceil(l/2)];if(c==='artificer')return t[Math.ceil(l/2)];if(c==='1/3')return l<3?[]:t[Math.ceil(l/3)];return [];}
function stats(s){const c=info(s),l=s.level,p=2+Math.floor((l-1)/4),m=Object.fromEntries(Object.entries(s.abilities).map(([k,v])=>[k,mod(v)])),cast=casting(s),ss=slots(s);let ac=s.acBase+(s.armorDexCap===undefined?m.dex:Math.min(m.dex,s.armorDexCap))+s.acBonus;
 if(s.armorMode==='fixed')ac=s.acBase+s.acBonus;
 if(s.armorMode==='barbarian')ac=10+m.dex+m.con+s.acBonus;
 if(s.armorMode==='monk')ac=10+m.dex+m.wis+s.acBonus;
 return {prof:p,mods:m,maxHP:Math.max(1,s.hpBase+l*m.con),ac,dc:8+p+m[cast.ability],attack:p+m[cast.ability],inspirationMax:Math.max(1,m.cha),inspirationDie:R().die(l),hitDice:l,hitDie:c.die,slots:ss,known:cast.known+(sub(s)?.name==='College of Lore'&&l>=6?2:0),cantrips:cast.cantrips,prepared:cast.type==='prepared'||cast.type==='book'?Math.max(1,m[cast.ability]+(['artificer','paladin'].includes(id(s))?Math.floor(l/2):l)):0,initiative:m.dex+(id(s)==='bard'&&l>=2?Math.floor(p/2):0),songDie:id(s)==='bard'&&l>=2?R().song(l):0};}
function member(sp,s){if(sp.level===0&&(s.classChoices?.['Pact Boon']||[]).includes('pact-of-the-tome-PHB'))return true;const lists=sp.classes||D.spellClasses[sp.id]||[];if(id(s)==='bard')return sp.bard&&(!sp.optionalBard||s.progression.expanded);if(['fighter','rogue'].includes(id(s))&&casting(s).caster)return lists.includes('wizard');return lists.includes(id(s));}
const spellToken=t=>String(t).split('|')[0].toLowerCase().replace(/[^a-z0-9]/g,'');
function lookupSpell(s,t){const key=spellToken(t);return R().allSpells(s).find(x=>spellToken(x.english||x.name)===key||spellToken(x.id)===key);}
function granted(s){const result={prepared:[],known:[],expanded:[],choices:[]};for(const grant of sub(s)?.spells||[])for(const mode of ['prepared','known','expanded'])for(const [key,values] of Object.entries(grant[mode]||{})){const threshold=key.startsWith('s')?Number(key.slice(1))<=slots(s).length:Number(key)<=s.level;if(!threshold)continue;for(const val of Array.isArray(values)?values:[]){if(typeof val==='string'){const sp=lookupSpell(s,val);if(sp)result[mode].push(sp.id);}else result.choices.push(val);}}return result;}
function usable(s){const mode=casting(s).type,g=granted(s);return [...new Set([...s.known.filter(x=>{const sp=R().allSpells(s).find(y=>y.id===x);return sp?.level===0||!['book','prepared'].includes(mode)||(s.prepared||[]).includes(x);}),...s.extras,...g.prepared,...g.known,...Object.values(s.arcanum||{})])];}
function ritualAllowed(s,sp){if(!sp.ritual)return false;if(s.extras.includes(sp.id))return true;const c=id(s);if(c==='wizard')return s.known.includes(sp.id);return ['bard','cleric','druid','artificer'].includes(c)&&usable(s).includes(sp.id);}
function resources(s){const c=id(s),l=s.level,m=stats(s).mods,p=stats(s).prof,out=[];const add=(id,name,max,reset,text,action='manual')=>out.push({id,name,max,reset,text,action});
 if(c==='barbarian')add('rage','Rabia',l===20?999:l>=17?6:l>=12?5:l>=6?4:l>=3?3:2,'long','Acción adicional para entrar en rabia. Duración 1 minuto; revisá mantenimiento y beneficios del rasgo. No podés lanzar ni concentrar conjuros mientras dura. Nivel 20: usos ilimitados.','bonus');
 if(c==='fighter'){add('second-wind','Segundo aliento',1,'short','Acción adicional: recuperá 1d10 + nivel de guerrero PG. Registrá la curación obtenida.','bonus');if(l>=2)add('action-surge','Acción súbita',l>=17?2:1,'short','Después de registrar tu primera acción del turno, usá este botón para habilitar una segunda acción. Como máximo un uso por turno. No da otra acción adicional (bonus).','free');if(l>=9)add('indomitable','Indomable',l>=17?3:l>=13?2:1,'long','Repetí una salvación fallida; debés usar el nuevo resultado.');}
 if(c==='monk'&&l>=2)add('ki','Puntos de ki',l,'short','Ráfaga de golpes, Defensa paciente y Paso del viento cuestan 1 punto y una acción adicional. Otros rasgos tienen sus propios costes. Requiere al menos 30 minutos de meditación dentro del descanso.');
 if(c==='sorcerer'&&l>=2)add('sorcery','Puntos de hechicería',l,'long','Reservá el coste indicado por cada Metamagia. Crear espacios o convertirlos usa una acción adicional; no se realiza automáticamente al ajustar este contador.');
 if(c==='cleric'&&l>=2)add('channel','Canalizar divinidad',l>=18?3:l>=6?2:1,'short','Elegí Expulsar muertos vivientes u otra opción de tu dominio. Comparten usos.');
 if(c==='paladin'){add('lay-on-hands','Imposición de manos',l*5,'long','Acción: gastá puntos para curar por toque. Gastar 5 puede neutralizar un veneno o curar una enfermedad. No afecta muertos vivientes ni constructos.','action');add('divine-sense','Sentido divino',Math.max(1,1+m.cha),'long','Acción: detectá celestiales, infernales y muertos vivientes a 60 pies sin cobertura total, hasta el fin de tu siguiente turno.','action');if(l>=3)add('channel','Canalizar divinidad',1,'short','Usá una opción de tu juramento. Comparten un uso.');if(l>=14)add('cleansing','Toque purificador',Math.max(1,m.cha),'long','Acción: terminá un conjuro sobre vos o una criatura voluntaria que toques.','action');}
 if(c==='druid'&&l>=2)add('wild-shape','Forma salvaje',l===20?999:2,'short','Transformación según tu círculo y límites de nivel, VD y movimiento. Conservá tus PG originales: anotá los de la forma aparte. Nivel 20: usos ilimitados.','action');
 if(c==='wizard')add('arcane-recovery','Recuperación arcana',1,'long','Una vez al día, tras un descanso corto: recuperá espacios que sumen hasta '+Math.ceil(l/2)+' niveles, ninguno de nivel 6 o superior. Ajustalos después de registrar el uso.');
 if(c==='artificer'&&l>=7)add('flash','Destello de genialidad',Math.max(1,m.int),'long','Reacción: sumá INT a una prueba o salvación tuya o de otra criatura visible a 30 pies.','reaction');
 if(c==='warlock')for(const [lv,id] of Object.entries(s.arcanum||{}))add('arcanum'+lv,'Arcanum nivel '+lv,1,'long','Lanzamiento del conjuro elegido una vez por descanso largo, sin gastar espacio de pacto.');
 const sc=sub(s)?.name;
 if(c==='fighter'&&sc==='Battle Master'&&l>=3)add('superiority','Dados de superioridad',l>=15?6:l>=7?5:4,'short','d'+(l>=18?12:l>=10?10:8)+'. Elegí una maniobra y cumplí su desencadenante.');
 return out;}
function spent(s,res){return (s.classSpent||{})[res.id]??(s.classResourcesConfirmed===false?null:0);}
function spend(s,rid,n){const res=resources(s).find(x=>x.id===rid);if(!res||spent(s,res)===null||!Number.isInteger(n)||n<1||spent(s,res)+n>res.max)throw Error('No alcanza ese recurso.');s.classSpent=s.classSpent||{};s.classSpent[rid]=spent(s,res)+n;}
function reset(s,type){s.raging=false;s.classSpent=s.classSpent||{};for(const res of resources(s))if(type==='long'||res.reset==='short')s.classSpent[res.id]=0;if(id(s)==='warlock'&&type==='short')s.slotsSpent=Array(9).fill(0);if(id(s)==='bard'&&(type==='long'||s.level>=5))s.inspirationSpent=0;}
function choices(s){const sc=sub(s),all=[...info(s).choices,...(sc?.choices||[])];return all.map(x=>{let count=Array.isArray(x.progression)?at(x.progression,s.level):Object.entries(x.progression).filter(([l])=>Number(l)<=s.level).sort((a,b)=>Number(b[0])-Number(a[0]))[0]?.[1]||0;return {name:x.name,types:x.featureType,count,options:D.options.filter(o=>o.types.some(t=>x.featureType.includes(t))&&o.level<=s.level)};}).filter(x=>x.count);}
function features(s,level=s.level){return [...info(s).features.filter(x=>!x.optional||s.optionalClassFeatures),...(sub(s)?.features||[])].filter(x=>x.level<=level);}
function asiLevels(s){return id(s)==='fighter'?[4,6,8,12,14,16,19]:id(s)==='rogue'?[4,8,10,12,16,19]:[4,8,12,16,19];}
function tasks(s){const d=stats(s),cast=casting(s),sp=R().allSpells(s),normal=s.known.map(id=>sp.find(x=>x.id===id)).filter(Boolean),can=normal.filter(x=>x.level===0&&!s.secretKnown.includes(x.id)).length,known=normal.filter(x=>x.level>0||s.secretKnown.includes(x.id)).length,result=[];
 if(s.level>=info(s).subclassLevel&&!sub(s))result.push('Elegí tu subclase.');
 if(can<d.cantrips)result.push('Elegí '+(d.cantrips-can)+' truco(s).');
 if(cast.type==='known'&&known<d.known)result.push('Aprendé '+(d.known-known)+' conjuro(s).');
 if(cast.type==='book'&&known<6+2*(s.level-1))result.push('Completá el libro: faltan al menos '+(6+2*(s.level-1)-known)+' conjuros de progresión.');
 if(['book','prepared'].includes(cast.type)&&(s.prepared||[]).length<d.prepared)result.push('Podés preparar '+(d.prepared-(s.prepared||[]).length)+' conjuro(s) más.');
 for(const c of choices(s)){const count=(s.classChoices?.[c.name]||[]).length;if(count<c.count)result.push('Elegí '+(c.count-count)+' opción(es) de '+c.name+'.');}
 if(id(s)==='warlock')for(const [l,sl] of [[11,6],[13,7],[15,8],[17,9]])if(s.level>=l&&!s.arcanum?.[sl])result.push('Elegí tu Arcanum de nivel '+sl+'.');
 const ex=id(s)==='rogue'?(s.level>=6?4:2):id(s)==='bard'?(s.level>=10?4:s.level>=3?2:0):0;if(s.expertise.length<ex)result.push('Elegí '+(ex-s.expertise.length)+' Pericia(s), o registrá herramientas según tu rasgo.');return result;}
function validate(s){if(!D.classes[id(s)])throw Error('Clase desconocida.');if(s.castingAbility&&!['str','dex','con','int','wis','cha'].includes(s.castingAbility))throw Error('Característica de lanzamiento inválida.');if(s.armorMode&&!['normal','medium','fixed','barbarian','monk'].includes(s.armorMode))throw Error('Fórmula de armadura inválida.');if(s.armorDexCap!==undefined&&(!Number.isInteger(s.armorDexCap)||s.armorDexCap<0||s.armorDexCap>30))throw Error('Límite de DES inválido.');if(s.classSubclass&&!D.subclasses.some(x=>x.id===s.classSubclass&&x.classId===id(s)))throw Error('Subclase incompatible.');const arr=(x)=>Array.isArray(x)&&x.length<=520&&x.every(v=>typeof v==='string'&&v.length<=100);for(const key of ['prepared'])if(s[key]!==undefined&&!arr(s[key]))throw Error('Repertorio inválido.');if(s.prepared?.some(x=>!s.known.includes(x)))throw Error('Prepará solo conjuros de tu repertorio o libro.');for(const k of ['classSpent','spellModes','arcanum','classChoices'])if(s[k]!==undefined&&(!s[k]||typeof s[k]!=='object'||Array.isArray(s[k])))throw Error('Datos de clase inválidos.');for(const v of Object.values(s.classSpent||{}))if(!Number.isInteger(v)||v<0||v>9999)throw Error('Recurso inválido.');for(const [k,v]of Object.entries(s.spellModes||{}))if(!s.extras.includes(k)||!['slot','free'].includes(v))throw Error('Modo de conjuro inválido.');for(const [k,v]of Object.entries(s.classChoices||{}))if(k.length>150||!arr(v))throw Error('Elecciones inválidas.');for(const [k,v]of Object.entries(s.arcanum||{}))if(id(s)!=='warlock'||![6,7,8,9].includes(Number(k))||s.level<11+(Number(k)-6)*2||!R().allSpells(s).some(x=>x.id===v&&x.level===Number(k)))throw Error('Arcanum inválido.');for(const k of ['race','background','languages','characterNotes','classNotes'])if(s[k]!==undefined&&(typeof s[k]!=='string'||s[k].length>20000))throw Error('Texto de personaje inválido.');if(s.speed!==undefined&&(!Number.isInteger(s.speed)||s.speed<0||s.speed>500))throw Error('Velocidad inválida.');}
function levelUp(s,choice){const next=clone(s);if(s.level>=20)throw Error('Ya estás en nivel 20.');const l=s.level+1,die=info(s).die,roll=choice.hpMethod==='rolled'?Number(choice.hpRoll):die/2+1;if(!Number.isInteger(roll)||roll<1||roll>die)throw Error('Tirada de PG inválida.');next.level=l;if(choice.subclass){next.classSubclass=choice.subclass;next.subclass=choice.subclass==='bard-college-of-eloquence'?'eloquence':'manual';}if(l>=info(next).subclassLevel&&!sub(next))throw Error('Elegí una subclase.');if(asiLevels(s).includes(l)){if(choice.asi==='scores'){for(const a of [choice.a1,choice.a2]){if(!Object.hasOwn(next.abilities,a))throw Error('Elegí las características.');if(++next.abilities[a]>20)throw Error('La mejora no puede superar 20.');}}else{const feat=root.Catalog.feats.find(x=>x.id===choice.feat);if(!feat||!choice.reviewed)throw Error('Elegí una dote y revisá sus requisitos.');next.progression.learnedFeats.push(feat.id);next.features.push({name:feat.name,text:'Dote: '+choice.featNotes});}}
 next.hpBase+=Math.max(1,roll+mod(next.abilities.con))-mod(next.abilities.con);if(next.hp!==null)next.hp=Math.min(next.hp,stats(next).maxHP);
 const before=slots(s),after=slots(next);if(casting(next).caster==='pact'){const used=s.slotsSpent[before.length-1];next.slotsSpent=Array(9).fill(0);next.slotsSpent[after.length-1]=used===null?null:Math.min(used,after[after.length-1]);}else after.forEach((n,i)=>{if(!before[i]&&n)next.slotsSpent[i]=0;});
 next.levelHistory.push({level:l,note:'Clase '+info(s).name+'. PG máximos '+stats(s).maxHP+' → '+stats(next).maxHP+'. Revisá las elecciones y los rasgos nuevos en Clase.'});return R().validate(next);}
root.Classes={id,info,sub,casting,slots,stats,member,granted,usable,ritualAllowed,resources,spent,spend,reset,choices,features,asiLevels,tasks,validate,levelUp};
})(typeof window!=='undefined'?window:globalThis);
