/* Nombres en castellano de subclases, rasgos de clase, opciones (invocaciones, maniobras, metamagia…) y dotes.
   Se aplican sobre los datos al cargar; el nombre original queda en `english` para búsquedas y enlaces.
   Se usan los nombres de las ediciones en español cuando existen. */
(function (root) {
  'use strict';
  const SUB = {
    'artificer-alchemist': 'Alquimista',
    'artificer-armorer': 'Armero',
    'artificer-artillerist': 'Artillero',
    'artificer-battle-smith': 'Herrero de batalla',
    'barbarian-path-of-the-berserker': 'Senda del Berserker',
    'barbarian-path-of-the-totem-warrior': 'Senda del Guerrero Totémico',
    'barbarian-path-of-the-battlerager': 'Senda del Furibundo de Batalla',
    'barbarian-path-of-the-ancestral-guardian': 'Senda del Guardián Ancestral',
    'barbarian-path-of-the-storm-herald': 'Senda del Heraldo de la Tormenta',
    'barbarian-path-of-the-zealot': 'Senda del Fanático',
    'barbarian-path-of-the-beast': 'Senda de la Bestia',
    'barbarian-path-of-wild-magic': 'Senda de la Magia Salvaje',
    'barbarian-path-of-the-giant': 'Senda del Gigante',
    'bard-college-of-lore': 'Colegio del Conocimiento',
    'bard-college-of-valor': 'Colegio del Valor',
    'bard-college-of-glamour': 'Colegio del Glamour',
    'bard-college-of-swords': 'Colegio de las Espadas',
    'bard-college-of-whispers': 'Colegio de los Susurros',
    'bard-college-of-creation': 'Colegio de la Creación',
    'bard-college-of-eloquence': 'Colegio de la Elocuencia',
    'bard-college-of-spirits': 'Colegio de los Espíritus',
    'cleric-knowledge-domain': 'Dominio del Conocimiento',
    'cleric-life-domain': 'Dominio de la Vida',
    'cleric-light-domain': 'Dominio de la Luz',
    'cleric-nature-domain': 'Dominio de la Naturaleza',
    'cleric-tempest-domain': 'Dominio de la Tempestad',
    'cleric-trickery-domain': 'Dominio del Engaño',
    'cleric-war-domain': 'Dominio de la Guerra',
    'cleric-death-domain': 'Dominio de la Muerte',
    'cleric-arcana-domain': 'Dominio Arcano',
    'cleric-forge-domain': 'Dominio de la Forja',
    'cleric-grave-domain': 'Dominio de la Tumba',
    'cleric-order-domain': 'Dominio del Orden',
    'cleric-peace-domain': 'Dominio de la Paz',
    'cleric-twilight-domain': 'Dominio del Ocaso',
    'druid-circle-of-the-land': 'Círculo de la Tierra',
    'druid-circle-of-the-moon': 'Círculo de la Luna',
    'druid-circle-of-dreams': 'Círculo de los Sueños',
    'druid-circle-of-the-shepherd': 'Círculo del Pastor',
    'druid-circle-of-spores': 'Círculo de las Esporas',
    'druid-circle-of-stars': 'Círculo de las Estrellas',
    'druid-circle-of-wildfire': 'Círculo del Fuego Salvaje',
    'fighter-battle-master': 'Maestro de Batalla',
    'fighter-champion': 'Campeón',
    'fighter-eldritch-knight': 'Caballero Arcano',
    'fighter-purple-dragon-knight-banneret': 'Caballero del Dragón Púrpura (Abanderado)',
    'fighter-arcane-archer': 'Arquero Arcano',
    'fighter-cavalier': 'Caballero',
    'fighter-samurai': 'Samurái',
    'fighter-echo-knight': 'Caballero del Eco',
    'fighter-psi-warrior': 'Guerrero Psiónico',
    'fighter-rune-knight': 'Caballero Rúnico',
    'monk-way-of-shadow': 'Camino de la Sombra',
    'monk-way-of-the-four-elements': 'Camino de los Cuatro Elementos',
    'monk-way-of-the-open-hand': 'Camino de la Mano Abierta',
    'monk-way-of-the-long-death': 'Camino de la Larga Muerte',
    'monk-way-of-the-drunken-master': 'Camino del Maestro Borracho',
    'monk-way-of-the-kensei': 'Camino del Kensei',
    'monk-way-of-the-sun-soul': 'Camino del Alma Solar',
    'monk-way-of-mercy': 'Camino de la Misericordia',
    'monk-way-of-the-astral-self': 'Camino del Yo Astral',
    'monk-way-of-the-ascendant-dragon': 'Camino del Dragón Ascendente',
    'paladin-oath-of-devotion': 'Juramento de Entrega',
    'paladin-oath-of-the-ancients': 'Juramento de los Antiguos',
    'paladin-oath-of-vengeance': 'Juramento de Venganza',
    'paladin-oathbreaker': 'Rompejuramentos',
    'paladin-oath-of-the-crown': 'Juramento de la Corona',
    'paladin-oath-of-conquest': 'Juramento de Conquista',
    'paladin-oath-of-redemption': 'Juramento de Redención',
    'paladin-oath-of-glory': 'Juramento de Gloria',
    'paladin-oath-of-the-watchers': 'Juramento de los Vigilantes',
    'ranger-beast-master': 'Señor de las Bestias',
    'ranger-hunter': 'Cazador',
    'ranger-gloom-stalker': 'Acechador en la Penumbra',
    'ranger-horizon-walker': 'Caminante del Horizonte',
    'ranger-monster-slayer': 'Cazador de Monstruos',
    'ranger-fey-wanderer': 'Vagabundo Feérico',
    'ranger-swarmkeeper': 'Guardián del Enjambre',
    'ranger-drakewarden': 'Guardián del Dragón',
    'rogue-arcane-trickster': 'Bribón Arcano',
    'rogue-assassin': 'Asesino',
    'rogue-thief': 'Ladrón',
    'rogue-inquisitive': 'Inquisitivo',
    'rogue-mastermind': 'Cerebro',
    'rogue-scout': 'Explorador',
    'rogue-swashbuckler': 'Espadachín',
    'rogue-phantom': 'Fantasma',
    'rogue-soulknife': 'Cuchilla Psíquica',
    'sorcerer-draconic-bloodline': 'Linaje Dracónico',
    'sorcerer-wild-magic': 'Magia Salvaje',
    'sorcerer-divine-soul': 'Alma Divina',
    'sorcerer-shadow-magic': 'Magia de las Sombras',
    'sorcerer-storm-sorcery': 'Hechicería de la Tormenta',
    'sorcerer-aberrant-mind': 'Mente Aberrante',
    'sorcerer-clockwork-soul': 'Alma Mecánica',
    'sorcerer-lunar-sorcery': 'Hechicería Lunar',
    'warlock-the-archfey': 'El Archihada',
    'warlock-the-fiend': 'El Infernal',
    'warlock-the-great-old-one': 'El Primigenio',
    'warlock-the-undying': 'El Imperecedero',
    'warlock-the-celestial': 'El Celestial',
    'warlock-the-hexblade': 'El Filo Maldito',
    'warlock-the-fathomless': 'El Insondable',
    'warlock-the-genie': 'El Genio',
    'warlock-the-undead': 'El No Muerto',
    'wizard-school-of-abjuration': 'Escuela de Abjuración',
    'wizard-school-of-conjuration': 'Escuela de Conjuración',
    'wizard-school-of-divination': 'Escuela de Adivinación',
    'wizard-school-of-enchantment': 'Escuela de Encantamiento',
    'wizard-school-of-evocation': 'Escuela de Evocación',
    'wizard-school-of-illusion': 'Escuela de Ilusionismo',
    'wizard-school-of-necromancy': 'Escuela de Nigromancia',
    'wizard-school-of-transmutation': 'Escuela de Transmutación',
    'wizard-war-magic': 'Magia de Guerra',
    'wizard-chronurgy-magic': 'Magia de Cronurgia',
    'wizard-graviturgy-magic': 'Magia de Graviturgia',
    'wizard-bladesinging': 'Canto de la Hoja',
    'wizard-order-of-scribes': 'Orden de los Escribas',
  };
  const CD = 'Canalizar divinidad: ';
  const FEAT = {
    // Rasgos de clase
    'Optional Rule: Firearm Proficiency': 'Regla opcional: competencia con armas de fuego',
    'Magical Tinkering': 'Retoques mágicos',
    Spellcasting: 'Lanzamiento de conjuros',
    'Tools Required': 'Herramientas necesarias',
    'Cantrips (0-Level Spells)': 'Trucos (conjuros de nivel 0)',
    'Preparing and Casting Spells': 'Preparar y lanzar conjuros',
    'Spellcasting Ability': 'Aptitud mágica',
    'Ritual Casting': 'Lanzamiento ritual',
    'Infuse Item': 'Infundir objeto',
    'Artificer Infusions': 'Infusiones de artífice',
    'Infusing an Item': 'Infundir un objeto',
    'Artificer Specialist': 'Especialista artífice',
    'The Right Tool for the Job': 'La herramienta adecuada',
    'Ability Score Improvement': 'Mejora de característica',
    'Artificer Specialist Feature': 'Rasgo de especialista',
    'Tool Expertise': 'Pericia con herramientas',
    'Flash of Genius': 'Destello de genialidad',
    'Magic Item Adept': 'Adepto de objetos mágicos',
    'Spell-Storing Item': 'Objeto almacén de conjuros',
    'Magic Item Savant': 'Erudito de objetos mágicos',
    'Magic Item Master': 'Maestro de objetos mágicos',
    'Soul of Artifice': 'Alma del artificio',
    Rage: 'Furia',
    'Unarmored Defense': 'Defensa sin armadura',
    'Danger Sense': 'Sentir el peligro',
    'Reckless Attack': 'Ataque temerario',
    'Primal Path': 'Senda primigenia',
    'Primal Knowledge': 'Conocimiento primigenio',
    'Extra Attack': 'Ataque adicional',
    'Fast Movement': 'Movimiento rápido',
    'Path Feature': 'Rasgo de senda',
    'Path feature': 'Rasgo de senda',
    'Feral Instinct': 'Instinto salvaje',
    'Instinctive Pounce': 'Abalanzarse por instinto',
    'Brutal Critical (1 die)': 'Crítico brutal (1 dado)',
    'Relentless Rage': 'Furia implacable',
    'Brutal Critical (2 dice)': 'Crítico brutal (2 dados)',
    'Persistent Rage': 'Furia persistente',
    'Brutal Critical (3 dice)': 'Crítico brutal (3 dados)',
    'Indomitable Might': 'Poderío indomable',
    'Primal Champion': 'Campeón primigenio',
    'Bardic Inspiration': 'Inspiración bárdica',
    Cantrips: 'Trucos',
    'Spell Slots': 'Espacios de conjuro',
    'Spells Known of 1st Level and Higher': 'Conjuros conocidos de nivel 1 o superior',
    'Spellcasting Focus': 'Canalizador mágico',
    'Jack of All Trades': 'Polivalente',
    'Song of Rest (d6)': 'Canción de descanso (d6)',
    'Magical Inspiration': 'Inspiración mágica',
    'Bard College': 'Colegio de bardo',
    Expertise: 'Pericia',
    'Bardic Versatility': 'Versatilidad bárdica',
    'Bardic Inspiration (d8)': 'Inspiración bárdica (d8)',
    'Font of Inspiration': 'Fuente de inspiración',
    Countercharm: 'Contraencantamiento',
    'Bard College feature': 'Rasgo de colegio',
    'Song of Rest (d8)': 'Canción de descanso (d8)',
    'Bardic Inspiration (d10)': 'Inspiración bárdica (d10)',
    'Magical Secrets': 'Secretos mágicos',
    'Song of Rest (d10)': 'Canción de descanso (d10)',
    'Bardic Inspiration (d12)': 'Inspiración bárdica (d12)',
    'Song of Rest (d12)': 'Canción de descanso (d12)',
    'Superior Inspiration': 'Inspiración superior',
    'Divine Domain': 'Dominio divino',
    'Domain Spells': 'Conjuros de dominio',
    'Channel Divinity': 'Canalizar divinidad',
    'Channel Divinity: Harness Divine Power': CD + 'aprovechar el poder divino',
    'Divine Domain feature': 'Rasgo de dominio',
    'Cantrip Versatility': 'Versatilidad de trucos',
    'Destroy Undead (CR 1/2)': 'Destruir muertos vivientes (VD 1/2)',
    'Destroy Undead (CR 1)': 'Destruir muertos vivientes (VD 1)',
    'Divine Intervention': 'Intervención divina',
    'Destroy Undead (CR 2)': 'Destruir muertos vivientes (VD 2)',
    'Destroy Undead (CR 3)': 'Destruir muertos vivientes (VD 3)',
    'Destroy Undead (CR 4)': 'Destruir muertos vivientes (VD 4)',
    'Divine Intervention Improvement': 'Mejora de intervención divina',
    Druidic: 'Druídico',
    'Wild Shape': 'Forma salvaje',
    'Wild Companion': 'Compañero salvaje',
    'Druid Circle': 'Círculo druídico',
    'Wild Shape Improvement': 'Mejora de forma salvaje',
    'Druid Circle feature': 'Rasgo de círculo',
    'Timeless Body': 'Cuerpo atemporal',
    'Beast Spells': 'Conjuros de bestia',
    Archdruid: 'Archidruida',
    'Fighting Style': 'Estilo de combate',
    'Second Wind': 'Tomar aliento',
    'Action Surge': 'Oleada de acción',
    'Martial Archetype': 'Arquetipo marcial',
    'Martial Versatility': 'Versatilidad marcial',
    'Martial Archetype feature': 'Rasgo de arquetipo',
    Indomitable: 'Indomable',
    'Extra Attack (2)': 'Ataque adicional (2)',
    'Indomitable (two uses)': 'Indomable (dos usos)',
    'Action Surge (two uses)': 'Oleada de acción (dos usos)',
    'Indomitable (three uses)': 'Indomable (tres usos)',
    'Extra Attack (3)': 'Ataque adicional (3)',
    'Martial Arts': 'Artes marciales',
    Ki: 'Ki',
    'Dedicated Weapon': 'Arma dedicada',
    'Unarmored Movement': 'Movimiento sin armadura',
    'Deflect Missiles': 'Desviar proyectiles',
    'Monastic Tradition': 'Tradición monástica',
    'Ki-Fueled Attack': 'Ataque potenciado por ki',
    'Slow Fall': 'Caída lenta',
    'Quickened Healing': 'Curación acelerada',
    'Stunning Strike': 'Golpe aturdidor',
    'Focused Aim': 'Puntería concentrada',
    'Ki-Empowered Strikes': 'Golpes potenciados por ki',
    'Monastic Tradition feature': 'Rasgo de tradición',
    Evasion: 'Evasión',
    'Stillness of Mind': 'Mente en calma',
    'Unarmored Movement improvement': 'Mejora de movimiento sin armadura',
    'Purity of Body': 'Pureza corporal',
    'Tongue of the Sun and Moon': 'Lengua del sol y la luna',
    'Diamond Soul': 'Alma de diamante',
    'Empty Body': 'Cuerpo vacío',
    'Perfect Self': 'Perfección personal',
    'Divine Sense': 'Sentidos divinos',
    'Lay on Hands': 'Imposición de manos',
    'Divine Smite': 'Castigo divino',
    'Divine Health': 'Salud divina',
    'Sacred Oath': 'Juramento sagrado',
    'Oath Spells': 'Conjuros de juramento',
    'Breaking Your Oath': 'Romper tu juramento',
    'Aura of Protection': 'Aura de protección',
    'Sacred Oath feature': 'Rasgo de juramento',
    'Aura of Courage': 'Aura de valor',
    'Improved Divine Smite': 'Castigo divino mejorado',
    'Cleansing Touch': 'Toque purificador',
    'Aura improvements': 'Mejora de auras',
    'Favored Enemy': 'Enemigo predilecto',
    'Favored Foe': 'Enemigo favorito',
    'Natural Explorer': 'Explorador nato',
    'Deft Explorer': 'Explorador hábil',
    Canny: 'Astuto',
    'Ranger Archetype': 'Arquetipo de explorador',
    'Primeval Awareness': 'Consciencia primigenia',
    'Primal Awareness': 'Percepción primigenia',
    'Favored Enemy and Natural Explorer improvements': 'Mejoras de enemigo predilecto y explorador nato',
    'Deft Explorer Improvement': 'Mejora de explorador hábil',
    Roving: 'Trotamundos',
    'Ranger Archetype feature': 'Rasgo de arquetipo',
    "Land's Stride": 'Zancada terrestre',
    'Hide in Plain Sight': 'Esconderse a plena vista',
    "Nature's Veil": 'Velo de la naturaleza',
    'Natural Explorer improvement': 'Mejora de explorador nato',
    Tireless: 'Incansable',
    Vanish: 'Desvanecerse',
    'Favored Enemy improvement': 'Mejora de enemigo predilecto',
    'Feral Senses': 'Sentidos salvajes',
    'Foe Slayer': 'Asesino de enemigos',
    'Sneak Attack': 'Ataque furtivo',
    "Thieves' Cant": 'Jerga de ladrones',
    'Cunning Action': 'Acción astuta',
    'Roguish Archetype': 'Arquetipo de pícaro',
    'Steady Aim': 'Apuntar con calma',
    'Uncanny Dodge': 'Esquiva asombrosa',
    'Roguish Archetype feature': 'Rasgo de arquetipo',
    'Reliable Talent': 'Talento fiable',
    Blindsense: 'Sentir sin ver',
    'Slippery Mind': 'Mente escurridiza',
    Elusive: 'Escurridizo',
    'Stroke of Luck': 'Golpe de suerte',
    'Sorcerous Origin': 'Origen hechicero',
    'Font of Magic': 'Fuente de magia',
    Metamagic: 'Metamagia',
    'Metamagic Options': 'Opciones de metamagia',
    'Sorcerous Versatility': 'Versatilidad hechicera',
    'Magical Guidance': 'Guía mágica',
    'Sorcerous Origin feature': 'Rasgo de origen',
    'Sorcerous Restoration': 'Restablecimiento hechicero',
    'Pact Magic': 'Magia de pacto',
    'Otherworldly Patron': 'Patrón de otro mundo',
    'Eldritch Invocations': 'Invocaciones sobrenaturales',
    'Pact Boon': 'Don del pacto',
    'Eldritch Versatility': 'Versatilidad sobrenatural',
    'Otherworldly Patron feature': 'Rasgo de patrón',
    'Mystic Arcanum (6th level)': 'Arcanum místico (nivel 6)',
    'Mystic Arcanum (7th level)': 'Arcanum místico (nivel 7)',
    'Mystic Arcanum (8th level)': 'Arcanum místico (nivel 8)',
    'Mystic Arcanum (9th level)': 'Arcanum místico (nivel 9)',
    'Eldritch Master': 'Maestro sobrenatural',
    'Arcane Recovery': 'Recuperación arcana',
    Spellbook: 'Libro de conjuros',
    'Learning Spells of 1st Level and Higher': 'Aprender conjuros de nivel 1 o superior',
    'Your Spellbook': 'Tu libro de conjuros',
    'Arcane Tradition': 'Tradición arcana',
    'Cantrip Formulas': 'Fórmulas de trucos',
    'Arcane Tradition feature': 'Rasgo de tradición',
    'Spell Mastery': 'Dominio de conjuros',
    'Signature Spells': 'Conjuros distintivos',
    // Rasgos de subclase
    'Alchemical Savant': 'Erudito alquímico',
    'Restorative Reagents': 'Reactivos reconstituyentes',
    'Chemical Mastery': 'Dominio químico',
    'Armor Modifications': 'Modificaciones de armadura',
    'Perfected Armor': 'Armadura perfeccionada',
    'Arcane Firearm': 'Arma de fuego arcana',
    'Explosive Cannon': 'Cañón explosivo',
    'Fortified Position': 'Posición fortificada',
    'Arcane Jolt': 'Sacudida arcana',
    'Improved Defender': 'Defensor mejorado',
    'Mindless Rage': 'Furia descerebrada',
    'Intimidating Presence': 'Presencia intimidante',
    Retaliation: 'Represalia',
    'Aspect of the Beast': 'Aspecto de la bestia',
    'Spirit Walker': 'Caminante espiritual',
    'Totemic Attunement': 'Sintonía totémica',
    'Reckless Abandon': 'Desenfreno temerario',
    'Battlerager Charge': 'Carga del furibundo',
    'Spiked Retribution': 'Represalia con pinchos',
    'Spirit Shield': 'Escudo espiritual',
    'Consult the Spirits': 'Consultar a los espíritus',
    'Vengeful Ancestors': 'Ancestros vengativos',
    'Storm Soul': 'Alma de la tormenta',
    'Shielding Storm': 'Tormenta protectora',
    'Raging Storm': 'Tormenta furiosa',
    'Fanatical Focus': 'Concentración fanática',
    'Zealous Presence': 'Presencia fervorosa',
    'Rage beyond Death': 'Furia más allá de la muerte',
    'Bestial Soul': 'Alma bestial',
    'Infectious Fury': 'Furia contagiosa',
    'Call the Hunt': 'Llamar a la cacería',
    'Bolstering Magic': 'Magia reconfortante',
    'Unstable Backlash': 'Reacción inestable',
    'Controlled Surge': 'Oleada controlada',
    'Elemental Cleaver': 'Hendedor elemental',
    'Mighty Impel': 'Impulso poderoso',
    'Demiurgic Colossus': 'Coloso demiúrgico',
    'Additional Magical Secrets': 'Secretos mágicos adicionales',
    'Peerless Skill': 'Habilidad sin par',
    'Battle Magic': 'Magia de batalla',
    'Mantle of Majesty': 'Manto de majestad',
    'Unbreakable Majesty': 'Majestad inquebrantable',
    "Master's Flourish": 'Floritura del maestro',
    'Mantle of Whispers': 'Manto de susurros',
    'Shadow Lore': 'Saber de las sombras',
    'Animating Performance': 'Actuación animadora',
    'Creative Crescendo': 'Crescendo creativo',
    'Unfailing Inspiration': 'Inspiración infalible',
    'Universal Speech': 'Habla universal',
    'Infectious Inspiration': 'Inspiración contagiosa',
    'Spirit Session': 'Sesión espiritista',
    'Mystical Connection': 'Conexión mística',
    'Spirit Tales': 'Relatos de los espíritus',
    'Channel Divinity: Knowledge of the Ages': CD + 'conocimiento de las eras',
    'Channel Divinity: Read Thoughts': CD + 'leer pensamientos',
    'Potent Spellcasting': 'Lanzamiento potente',
    'Blessed Strikes': 'Golpes benditos',
    'Visions of the Past': 'Visiones del pasado',
    'Channel Divinity: Preserve Life': CD + 'preservar la vida',
    'Blessed Healer': 'Sanador bendito',
    'Divine Strike': 'Golpe divino',
    'Supreme Healing': 'Curación suprema',
    'Channel Divinity: Radiance of the Dawn': CD + 'resplandor del alba',
    'Improved Flare': 'Destello mejorado',
    'Corona of Light': 'Corona de luz',
    'Channel Divinity: Charm Animals and Plants': CD + 'hechizar animales y plantas',
    'Dampen Elements': 'Amortiguar elementos',
    'Master of Nature': 'Señor de la naturaleza',
    'Channel Divinity: Destructive Wrath': CD + 'ira destructora',
    'Thunderbolt Strike': 'Golpe de rayo',
    Stormborn: 'Nacido de la tormenta',
    'Channel Divinity: Invoke Duplicity': CD + 'invocar duplicidad',
    'Channel Divinity: Cloak of Shadows': CD + 'manto de sombras',
    'Improved Duplicity': 'Duplicidad mejorada',
    'Channel Divinity: Guided Strike': CD + 'golpe guiado',
    "Channel Divinity: War God's Blessing": CD + 'bendición del dios de la guerra',
    'Avatar of Battle': 'Avatar de batalla',
    'Channel Divinity: Touch of Death': CD + 'toque de la muerte',
    'Inescapable Destruction': 'Destrucción ineludible',
    'Improved Reaper': 'Segador mejorado',
    'Channel Divinity: Arcane Abjuration': CD + 'abjuración arcana',
    'Spell Breaker': 'Rompeconjuros',
    'Arcane Mastery': 'Maestría arcana',
    "Channel Divinity: Artisan's Blessing": CD + 'bendición del artesano',
    'Soul of the Forge': 'Alma de la forja',
    'Saint of Forge and Fire': 'Santo de la forja y el fuego',
    'Channel Divinity: Path to the Grave': CD + 'camino a la tumba',
    "Sentinel at Death's Door": 'Centinela a las puertas de la muerte',
    'Keeper of Souls': 'Guardián de almas',
    "Channel Divinity: Order's Demand": CD + 'exigencia del orden',
    'Embodiment of the Law': 'Encarnación de la ley',
    "Order's Wrath": 'Ira del orden',
    'Channel Divinity: Balm of Peace': CD + 'bálsamo de paz',
    'Protective Bond': 'Vínculo protector',
    'Expansive Bond': 'Vínculo expansivo',
    'Channel Divinity: Twilight Sanctuary': CD + 'santuario del ocaso',
    'Steps of Night': 'Pasos de la noche',
    'Twilight Shroud': 'Velo del ocaso',
    "Nature's Ward": 'Protección de la naturaleza',
    "Nature's Sanctuary": 'Santuario de la naturaleza',
    'Primal Strike': 'Golpe primigenio',
    'Elemental Wild Shape': 'Forma salvaje elemental',
    'Thousand Forms': 'Mil formas',
    'Hearth of Moonlight and Shadow': 'Hogar de luz de luna y sombra',
    'Hidden Paths': 'Senderos ocultos',
    'Walker in Dreams': 'Caminante de los sueños',
    'Mighty Summoner': 'Invocador poderoso',
    'Guardian Spirit': 'Espíritu guardián',
    'Faithful Summons': 'Invocación leal',
    'Fungal Infestation': 'Infestación fúngica',
    'Spreading Spores': 'Esporas que se extienden',
    'Fungal Body': 'Cuerpo fúngico',
    'Cosmic Omen': 'Presagio cósmico',
    'Twinkling Constellations': 'Constelaciones titilantes',
    'Full of Stars': 'Lleno de estrellas',
    'Enhanced Bond': 'Vínculo potenciado',
    'Cauterizing Flames': 'Llamas cauterizantes',
    'Blazing Revival': 'Renacer llameante',
    'Additional Maneuvers': 'Maniobras adicionales',
    'Additional Superiority Die': 'Dado de superioridad adicional',
    'Know Your Enemy': 'Conoce a tu enemigo',
    'Improved Combat Superiority (d10)': 'Superioridad en combate mejorada (d10)',
    Relentless: 'Implacable',
    'Improved Combat Superiority (d12)': 'Superioridad en combate mejorada (d12)',
    'Remarkable Athlete': 'Atleta excepcional',
    'Additional Fighting Style': 'Estilo de combate adicional',
    'Superior Critical': 'Crítico superior',
    Survivor: 'Superviviente',
    'War Magic': 'Magia de guerra',
    'Eldritch Strike': 'Golpe arcano',
    'Arcane Charge': 'Carga arcana',
    'Improved War Magic': 'Magia de guerra mejorada',
    'Royal Envoy': 'Enviado real',
    'Inspiring Surge': 'Oleada inspiradora',
    Bulwark: 'Baluarte',
    'Magic Arrow': 'Flecha mágica',
    'Curving Shot': 'Disparo curvo',
    'Additional Arcane Shot Option': 'Opción adicional de disparo arcano',
    'Ever-Ready Shot': 'Disparo siempre listo',
    'Warding Maneuver': 'Maniobra protectora',
    'Hold the Line': 'Mantener la línea',
    'Ferocious Charger': 'Carga feroz',
    'Vigilant Defender': 'Defensor vigilante',
    'Elegant Courtier': 'Cortesano elegante',
    'Tireless Spirit': 'Espíritu incansable',
    'Rapid Strike': 'Golpe rápido',
    'Strength before Death': 'Fuerza ante la muerte',
    'Echo Avatar': 'Avatar del eco',
    'Shadow Martyr': 'Mártir de sombra',
    'Reclaim Potential': 'Recuperar potencial',
    'Legion of One': 'Legión de uno',
    'Telekinetic Adept': 'Adepto telequinético',
    'Guarded Mind': 'Mente protegida',
    'Bulwark of Force': 'Baluarte de fuerza',
    'Telekinetic Master': 'Maestro telequinético',
    'Runic Shield': 'Escudo rúnico',
    'Additional Rune Known': 'Runa adicional',
    'Great Stature': 'Gran estatura',
    'Master of Runes': 'Maestro de runas',
    'Runic Juggernaut': 'Coloso rúnico',
    'Shadow Step': 'Paso de sombra',
    'Cloak of Shadows': 'Manto de sombras',
    Opportunist: 'Oportunista',
    'Extra Elemental Discipline': 'Disciplina elemental adicional',
    'Wholeness of Body': 'Integridad corporal',
    Tranquility: 'Tranquilidad',
    'Quivering Palm': 'Palma temblorosa',
    'Hour of Reaping': 'Hora de la cosecha',
    'Mastery of Death': 'Dominio de la muerte',
    'Touch of the Long Death': 'Toque de la larga muerte',
    'Tipsy Sway': 'Vaivén de borracho',
    "Drunkard's Luck": 'Suerte del borracho',
    'Intoxicated Frenzy': 'Frenesí ebrio',
    'One with the Blade': 'Uno con la hoja',
    'Magic Kensei Weapons': 'Armas kensei mágicas',
    'Deft Strike': 'Golpe hábil',
    'Sharpen the Blade': 'Afilar la hoja',
    'Unerring Accuracy': 'Precisión infalible',
    'Searing Arc Strike': 'Golpe de arco abrasador',
    'Searing Sunburst': 'Estallido solar abrasador',
    'Sun Shield': 'Escudo solar',
    "Physician's Touch": 'Toque del médico',
    'Flurry of Healing and Harm': 'Ráfaga de curación y daño',
    'Hand of Ultimate Mercy': 'Mano de la misericordia suprema',
    'Visage of the Astral Self': 'Rostro del yo astral',
    'Astral Sight': 'Visión astral',
    'Wisdom of the Spirit': 'Sabiduría del espíritu',
    'Word of the Spirit': 'Palabra del espíritu',
    'Body of the Astral Self': 'Cuerpo del yo astral',
    'Deflect Energy': 'Desviar energía',
    'Empowered Arms': 'Brazos potenciados',
    'Awakened Astral Self': 'Yo astral despierto',
    'Armor of the Spirit': 'Armadura del espíritu',
    'Astral Barrage': 'Andanada astral',
    'Wings Unfurled': 'Alas desplegadas',
    'Aspect of the Wyrm': 'Aspecto del wyrm',
    'Ascendant Aspect': 'Aspecto ascendente',
    'Aura of Devotion': 'Aura de devoción',
    'Purity of Spirit': 'Pureza de espíritu',
    'Holy Nimbus': 'Nimbo sagrado',
    'Aura of Warding': 'Aura de protección mágica',
    'Undying Sentinel': 'Centinela imperecedero',
    'Elder Champion': 'Campeón anciano',
    'Relentless Avenger': 'Vengador implacable',
    'Soul of Vengeance': 'Alma de venganza',
    'Avenging Angel': 'Ángel vengador',
    'Aura of Hate': 'Aura de odio',
    'Supernatural Resistance': 'Resistencia sobrenatural',
    'Dread Lord': 'Señor del terror',
    'Divine Allegiance': 'Lealtad divina',
    'Unyielding Spirit': 'Espíritu inquebrantable',
    'Exalted Champion': 'Campeón exaltado',
    'Aura of Conquest': 'Aura de conquista',
    'Scornful Rebuke': 'Reprimenda desdeñosa',
    'Invincible Conqueror': 'Conquistador invencible',
    'Aura of the Guardian': 'Aura del guardián',
    'Protective Spirit': 'Espíritu protector',
    'Emissary of Redemption': 'Emisario de la redención',
    'Aura of Alacrity': 'Aura de presteza',
    'Glorious Defense': 'Defensa gloriosa',
    'Living Legend': 'Leyenda viviente',
    'Aura of the Sentinel': 'Aura del centinela',
    'Vigilant Rebuke': 'Reprimenda vigilante',
    'Mortal Bulwark': 'Baluarte mortal',
    'Exceptional Training': 'Entrenamiento excepcional',
    'Bestial Fury': 'Furia bestial',
    'Share Spells': 'Compartir conjuros',
    'Defensive Tactics': 'Tácticas defensivas',
    Multiattack: 'Ataque múltiple',
    "Superior Hunter's Defense": 'Defensa superior del cazador',
    'Iron Mind': 'Mente de hierro',
    "Stalker's Flurry": 'Ráfaga del acechador',
    'Shadowy Dodge': 'Esquiva sombría',
    'Ethereal Step': 'Paso etéreo',
    'Distant Strike': 'Golpe distante',
    'Spectral Defense': 'Defensa espectral',
    'Supernatural Defense': 'Defensa sobrenatural',
    "Magic-User's Nemesis": 'Némesis de los magos',
    "Slayer's Counter": 'Contraataque del cazador',
    'Beguiling Twist': 'Giro cautivador',
    'Fey Reinforcements': 'Refuerzos feéricos',
    'Misty Wanderer': 'Vagabundo brumoso',
    'Writhing Tide': 'Marea retorcida',
    'Mighty Swarm': 'Enjambre poderoso',
    'Swarming Dispersal': 'Dispersión en enjambre',
    'Bond of Fang and Scale': 'Vínculo de colmillo y escama',
    "Drake's Breath": 'Aliento del draco',
    'Perfected Bond': 'Vínculo perfeccionado',
    'Magical Ambush': 'Emboscada mágica',
    'Versatile Trickster': 'Bribón versátil',
    'Spell Thief': 'Ladrón de conjuros',
    'Infiltration Expertise': 'Experto en infiltración',
    Impostor: 'Impostor',
    'Death Strike': 'Golpe mortal',
    'Supreme Sneak': 'Sigilo supremo',
    'Use Magic Device': 'Usar objeto mágico',
    "Thief's Reflexes": 'Reflejos de ladrón',
    'Steady Eye': 'Ojo firme',
    'Unerring Eye': 'Ojo infalible',
    'Eye for Weakness': 'Ojo para la debilidad',
    'Insightful Manipulator': 'Manipulador perspicaz',
    Misdirection: 'Desvío',
    'Soul of Deceit': 'Alma del engaño',
    'Superior Mobility': 'Movilidad superior',
    'Ambush Master': 'Maestro de la emboscada',
    'Sudden Strike': 'Golpe repentino',
    Panache: 'Desparpajo',
    'Elegant Maneuver': 'Maniobra elegante',
    'Master Duelist': 'Maestro duelista',
    'Tokens of the Departed': 'Recuerdos de los difuntos',
    'Ghost Walk': 'Paso fantasmal',
    "Death's Friend": 'Amigo de la muerte',
    'Soul Blades': 'Hojas del alma',
    'Psychic Veil': 'Velo psíquico',
    'Rend Mind': 'Desgarrar la mente',
    'Elemental Affinity': 'Afinidad elemental',
    'Dragon Wings': 'Alas de dragón',
    'Draconic Presence': 'Presencia dracónica',
    'Bend Luck': 'Torcer la suerte',
    'Controlled Chaos': 'Caos controlado',
    'Spell Bombardment': 'Bombardeo de conjuros',
    'Empowered Healing': 'Curación potenciada',
    'Otherworldly Wings': 'Alas de otro mundo',
    'Unearthly Recovery': 'Recuperación sobrenatural',
    'Hound of Ill Omen': 'Sabueso de mal agüero',
    'Shadow Walk': 'Caminar entre sombras',
    'Umbral Form': 'Forma umbría',
    'Heart of the Storm': 'Corazón de la tormenta',
    'Storm Guide': 'Guía de la tormenta',
    "Storm's Fury": 'Furia de la tormenta',
    'Wind Soul': 'Alma del viento',
    'Psionic Sorcery': 'Hechicería psiónica',
    'Psychic Defenses': 'Defensas psíquicas',
    'Revelation in Flesh': 'Revelación en la carne',
    'Warping Implosion': 'Implosión distorsionante',
    'Bastion of Law': 'Bastión de la ley',
    'Trance of Order': 'Trance del orden',
    'Clockwork Cavalcade': 'Cabalgata mecánica',
    'Lunar Boons': 'Dones lunares',
    'Waxing and Waning': 'Creciente y menguante',
    'Lunar Empowerment': 'Potenciación lunar',
    'Lunar Phenomenon': 'Fenómeno lunar',
    'Expanded Spell List': 'Lista de conjuros ampliada',
    'Misty Escape': 'Huida brumosa',
    'Beguiling Defenses': 'Defensas cautivadoras',
    'Dark Delirium': 'Delirio oscuro',
    "Dark One's Own Luck": 'Suerte del Oscuro',
    'Fiendish Resilience': 'Resistencia infernal',
    'Hurl Through Hell': 'Arrojar a través del infierno',
    'Entropic Ward': 'Protección entrópica',
    'Thought Shield': 'Escudo mental',
    'Create Thrall': 'Crear siervo',
    'Defy Death': 'Desafiar a la muerte',
    'Undying Nature': 'Naturaleza imperecedera',
    'Indestructible Life': 'Vida indestructible',
    'Radiant Soul': 'Alma radiante',
    'Celestial Resilience': 'Resistencia celestial',
    'Searing Vengeance': 'Venganza abrasadora',
    'Accursed Specter': 'Espectro maldito',
    'Armor of Hexes': 'Armadura de maleficios',
    'Master of Hexes': 'Señor de los maleficios',
    'Oceanic Soul': 'Alma oceánica',
    'Guardian Coil': 'Espiral guardiana',
    'Grasping Tentacles': 'Tentáculos aferradores',
    'Fathomless Plunge': 'Zambullida insondable',
    'Elemental Gift': 'Don elemental',
    'Sanctuary Vessel': 'Recipiente santuario',
    'Limited Wish': 'Deseo limitado',
    'Grave Touched': 'Tocado por la tumba',
    'Necrotic Husk': 'Cáscara necrótica',
    'Spirit Projection': 'Proyección espiritual',
    'Projected Ward': 'Protección proyectada',
    'Improved Abjuration': 'Abjuración mejorada',
    'Spell Resistance': 'Resistencia a los conjuros',
    'Benign Transposition': 'Transposición benigna',
    'Focused Conjuration': 'Conjuración concentrada',
    'Durable Summons': 'Invocaciones resistentes',
    'Expert Divination': 'Adivinación experta',
    'The Third Eye': 'El tercer ojo',
    'Greater Portent': 'Presagio mayor',
    'Instinctive Charm': 'Encanto instintivo',
    'Split Enchantment': 'Encantamiento dividido',
    'Alter Memories': 'Alterar recuerdos',
    'Potent Cantrip': 'Truco potente',
    'Empowered Evocation': 'Evocación potenciada',
    Overchannel: 'Sobrecanalizar',
    'Malleable Illusions': 'Ilusiones maleables',
    'Illusory Self': 'Yo ilusorio',
    'Illusory Reality': 'Realidad ilusoria',
    'Undead Thralls': 'Siervos no muertos',
    'Inured to Undeath': 'Inmune a la no muerte',
    'Command Undead': 'Comandar muertos vivientes',
    "Transmuter's Stone": 'Piedra del transmutador',
    Shapechanger: 'Cambiaformas',
    'Master Transmuter': 'Maestro transmutador',
    'Power Surge': 'Oleada de poder',
    'Durable Magic': 'Magia duradera',
    'Deflecting Shroud': 'Velo desviador',
    'Momentary Stasis': 'Estasis momentánea',
    'Arcane Abeyance': 'Suspensión arcana',
    'Convergent Future': 'Futuro convergente',
    'Gravity Well': 'Pozo de gravedad',
    'Violent Attraction': 'Atracción violenta',
    'Event Horizon': 'Horizonte de sucesos',
    'Song of Defense': 'Canción de defensa',
    'Song of Victory': 'Canción de victoria',
    'Manifest Mind': 'Mente manifiesta',
    'Master Scrivener': 'Maestro escriba',
    'One with the Word': 'Uno con la palabra',
  };
  // Grupos de elección (las claves guardadas en las fichas siguen en inglés).
  const CHOICE = {
    Infusions: 'Infusiones',
    'Fighting Style': 'Estilo de combate',
    Metamagic: 'Metamagia',
    'Eldritch Invocations': 'Invocaciones sobrenaturales',
    'Pact Boon': 'Don del pacto',
    Maneuvers: 'Maniobras',
    'Arcane Shots': 'Disparos arcanos',
    Runes: 'Runas',
    'Elemental Disciplines': 'Disciplinas elementales',
  };
  const OPT = {
    'Agonizing Blast': 'Descarga agonizante',
    Ambush: 'Emboscada',
    'Arcane Propulsion Armor': 'Armadura de propulsión arcana',
    Archery: 'Combate con arcos',
    'Armor of Magical Strength': 'Armadura de fuerza mágica',
    'Armor of Shadows': 'Armadura de sombras',
    'Ascendant Step': 'Paso ascendente',
    'Aspect of the Moon': 'Aspecto de la luna',
    'Bait and Switch': 'Cebo y cambio',
    'Banishing Arrow': 'Flecha desterradora',
    'Beast Speech': 'Habla con las bestias',
    'Beguiling Arrow': 'Flecha cautivadora',
    'Beguiling Influence': 'Influencia cautivadora',
    'Bewitching Whispers': 'Susurros embrujadores',
    'Blessed Warrior': 'Guerrero bendito',
    'Blind Fighting': 'Combate a ciegas',
    'Bond of the Talisman': 'Vínculo del talismán',
    'Book of Ancient Secrets': 'Libro de secretos antiguos',
    'Boots of the Winding Path': 'Botas del sendero sinuoso',
    Brace: 'Prepararse',
    'Breath of Winter': 'Aliento del invierno',
    'Bursting Arrow': 'Flecha explosiva',
    'Careful Spell': 'Conjuro cuidadoso',
    'Chains of Carceri': 'Cadenas de Carceri',
    'Clench of the North Wind': 'Garra del viento del norte',
    'Cloak of Flies': 'Manto de moscas',
    'Cloud Rune': 'Runa de las nubes',
    "Commander's Strike": 'Golpe del comandante',
    'Commanding Presence': 'Presencia dominante',
    Defense: 'Defensa',
    "Devil's Sight": 'Vista del diablo',
    'Disarming Attack': 'Ataque desarmante',
    'Distant Spell': 'Conjuro distante',
    'Distracting Strike': 'Golpe distractor',
    'Dreadful Word': 'Palabra temible',
    'Druidic Warrior': 'Guerrero druídico',
    Dueling: 'Duelo',
    'Eldritch Mind': 'Mente sobrenatural',
    'Eldritch Sight': 'Visión sobrenatural',
    'Eldritch Smite': 'Castigo sobrenatural',
    'Eldritch Spear': 'Lanza sobrenatural',
    'Elemental Attunement': 'Sintonía elemental',
    'Empowered Spell': 'Conjuro potenciado',
    'Enfeebling Arrow': 'Flecha debilitante',
    'Enhanced Arcane Focus': 'Canalizador arcano mejorado',
    'Enhanced Defense': 'Defensa mejorada',
    'Enhanced Weapon': 'Arma mejorada',
    'Eternal Mountain Defense': 'Defensa de la montaña eterna',
    'Evasive Footwork': 'Juego de pies evasivo',
    'Extended Spell': 'Conjuro extendido',
    'Eyes of the Rune Keeper': 'Ojos del guardián de runas',
    'Fangs of the Fire Snake': 'Colmillos de la serpiente de fuego',
    'Far Scribe': 'Escriba lejano',
    'Feinting Attack': 'Ataque de finta',
    'Fiendish Vigor': 'Vigor infernal',
    'Fire Rune': 'Runa de fuego',
    'Fist of Four Thunders': 'Puño de los cuatro truenos',
    'Flames of the Phoenix': 'Llamas del fénix',
    'Frost Rune': 'Runa de escarcha',
    'Gaze of Two Minds': 'Mirada de dos mentes',
    'Ghostly Gaze': 'Mirada fantasmal',
    'Gift of the Depths': 'Don de las profundidades',
    'Gift of the Ever-Living Ones': 'Don de los Eternos',
    'Gift of the Protectors': 'Don de los protectores',
    'Goading Attack': 'Ataque provocador',
    'Gong of the Summit': 'Gong de la cumbre',
    'Grappling Strike': 'Golpe apresador',
    'Grasp of Hadar': 'Garra de Hadar',
    'Grasping Arrow': 'Flecha aferradora',
    'Great Weapon Fighting': 'Combate con armas grandes',
    'Heightened Spell': 'Conjuro intensificado',
    'Helm of Awareness': 'Yelmo de alerta',
    'Hill Rune': 'Runa de las colinas',
    'Homunculus Servant': 'Sirviente homúnculo',
    'Improved Pact Weapon': 'Arma de pacto mejorada',
    Interception: 'Interceptar',
    'Investment of the Chain Master': 'Investidura del amo de la cadena',
    'Lance of Lethargy': 'Lanza de letargo',
    Lifedrinker: 'Bebevidas',
    'Lunging Attack': 'Ataque con estocada',
    'Maddening Hex': 'Maleficio enloquecedor',
    'Maneuvering Attack': 'Ataque de maniobra',
    'Mask of Many Faces': 'Máscara de muchos rostros',
    'Master of Myriad Forms': 'Señor de las mil formas',
    'Menacing Attack': 'Ataque amenazador',
    'Mind Sharpener': 'Afilamentes',
    'Minions of Chaos': 'Siervos del caos',
    'Mire the Mind': 'Embarrar la mente',
    'Mist Stance': 'Postura de niebla',
    'Misty Visions': 'Visiones brumosas',
    'One with Shadows': 'Uno con las sombras',
    'Otherworldly Leap': 'Salto de otro mundo',
    'Pact of the Blade': 'Pacto del filo',
    'Pact of the Chain': 'Pacto de la cadena',
    'Pact of the Talisman': 'Pacto del talismán',
    'Pact of the Tome': 'Pacto del tomo',
    Parry: 'Parada',
    'Piercing Arrow': 'Flecha perforante',
    'Precision Attack': 'Ataque preciso',
    Protection: 'Protección',
    'Protection of the Talisman': 'Protección del talismán',
    'Pushing Attack': 'Ataque de empuje',
    'Quick Toss': 'Lanzamiento rápido',
    'Quickened Spell': 'Conjuro acelerado',
    'Radiant Weapon': 'Arma radiante',
    Rally: 'Reagrupar',
    'Rebuke of the Talisman': 'Represalia del talismán',
    'Relentless Hex': 'Maleficio implacable',
    'Repeating Shot': 'Disparo repetido',
    'Repelling Blast': 'Descarga repulsora',
    'Replicate Magic Item': 'Replicar objeto mágico',
    'Repulsion Shield': 'Escudo de repulsión',
    'Resistant Armor': 'Armadura resistente',
    'Returning Weapon': 'Arma que regresa',
    'Ride the Wind': 'Cabalgar el viento',
    Riposte: 'Contraataque',
    'River of Hungry Flame': 'Río de llama hambrienta',
    'Rush of the Gale Spirits': 'Embestida de los espíritus del vendaval',
    'Sculptor of Flesh': 'Escultor de carne',
    'Seeking Arrow': 'Flecha buscadora',
    'Seeking Spell': 'Conjuro rastreador',
    'Shadow Arrow': 'Flecha de sombra',
    'Shape the Flowing River': 'Moldear el río fluyente',
    'Shroud of Shadow': 'Velo de sombra',
    'Sign of Ill Omen': 'Señal de mal agüero',
    'Spell-Refueling Ring': 'Anillo recargador de conjuros',
    'Stone Rune': 'Runa de piedra',
    'Storm Rune': 'Runa de tormenta',
    'Subtle Spell': 'Conjuro sutil',
    'Superior Technique': 'Técnica superior',
    'Sweeping Attack': 'Ataque de barrido',
    'Sweeping Cinder Strike': 'Golpe de ceniza arrolladora',
    'Tactical Assessment': 'Evaluación táctica',
    'Thief of Five Fates': 'Ladrón de cinco destinos',
    'Thirsting Blade': 'Filo sediento',
    'Thrown Weapon Fighting': 'Combate con armas arrojadizas',
    'Tomb of Levistus': 'Tumba de Levistus',
    'Transmuted Spell': 'Conjuro transmutado',
    "Trickster's Escape": 'Huida del embaucador',
    'Trip Attack': 'Ataque derribador',
    'Twinned Spell': 'Conjuro duplicado',
    'Two-Weapon Fighting': 'Combate con dos armas',
    'Unarmed Fighting': 'Combate sin armas',
    'Unbroken Air': 'Aire ininterrumpido',
    'Undying Servitude': 'Servidumbre imperecedera',
    'Visions of Distant Realms': 'Visiones de reinos lejanos',
    'Voice of the Chain Master': 'Voz del amo de la cadena',
    'Water Whip': 'Látigo de agua',
    'Wave of Rolling Earth': 'Ola de tierra ondulante',
    'Whispers of the Grave': 'Susurros de la tumba',
    'Witch Sight': 'Vista de bruja',
  };
  const FEATS = {
    'Aberrant Dragonmark': 'Marca de dragón aberrante',
    Actor: 'Actor',
    Alert: 'Alerta',
    'Artificer Initiate': 'Iniciado artífice',
    Athlete: 'Atleta',
    Cartomancer: 'Cartomante',
    Charger: 'Cargador',
    Chef: 'Chef',
    'Crossbow Expert': 'Experto en ballestas',
    Crusher: 'Aplastador',
    'Defensive Duelist': 'Duelista defensivo',
    'Dual Wielder': 'Combatiente con dos armas',
    'Dungeon Delver': 'Explorador de mazmorras',
    Durable: 'Duro',
    'Eldritch Adept': 'Adepto sobrenatural',
    'Elemental Adept': 'Adepto elemental',
    'Ember of the Fire Giant': 'Brasa del gigante de fuego',
    'Fey Touched': 'Tocado por las hadas',
    'Fighting Initiate': 'Iniciado en el combate',
    'Fury of the Frost Giant': 'Furia del gigante de escarcha',
    'Gift of the Chromatic Dragon': 'Don del dragón cromático',
    'Gift of the Gem Dragon': 'Don del dragón de gema',
    'Gift of the Metallic Dragon': 'Don del dragón metálico',
    Grappler: 'Apresador',
    'Great Weapon Master': 'Maestro de armas grandes',
    'Guile of the Cloud Giant': 'Astucia del gigante de las nubes',
    Gunner: 'Tirador con armas de fuego',
    Healer: 'Sanador',
    'Heavily Armored': 'Armadura pesada',
    'Heavy Armor Master': 'Maestro en armadura pesada',
    'Inspiring Leader': 'Líder inspirador',
    'Keen Mind': 'Mente aguda',
    'Keenness of the Stone Giant': 'Agudeza del gigante de piedra',
    'Lightly Armored': 'Armadura ligera',
    Linguist: 'Lingüista',
    Lucky: 'Afortunado',
    'Mage Slayer': 'Asesino de magos',
    'Magic Initiate': 'Iniciado en la magia',
    'Martial Adept': 'Adepto marcial',
    'Medium Armor Master': 'Maestro en armadura media',
    'Metamagic Adept': 'Adepto de la metamagia',
    Mobile: 'Móvil',
    'Moderately Armored': 'Armadura media',
    'Mounted Combatant': 'Combatiente montado',
    Observant: 'Observador',
    Piercer: 'Perforador',
    Poisoner: 'Envenenador',
    'Polearm Master': 'Maestro en armas de asta',
    Resilient: 'Resistente',
    'Ritual Caster': 'Lanzador ritual',
    'Rune Shaper': 'Moldeador de runas',
    'Savage Attacker': 'Atacante salvaje',
    Sentinel: 'Centinela',
    'Shadow Touched': 'Tocado por las sombras',
    Sharpshooter: 'Tirador de primera',
    'Shield Master': 'Maestro de escudos',
    'Skill Expert': 'Experto en habilidades',
    Skilled: 'Habilidoso',
    Skulker: 'Merodeador',
    Slasher: 'Tajador',
    'Soul of the Storm Giant': 'Alma del gigante de las tormentas',
    'Spell Sniper': 'Francotirador de conjuros',
    'Strike of the Giants': 'Golpe de los gigantes',
    'Tavern Brawler': 'Camorrista de taberna',
    Telekinetic: 'Telequinético',
    Telepathic: 'Telepático',
    Tough: 'Robusto',
    'Vigor of the Hill Giant': 'Vigor del gigante de las colinas',
    'War Caster': 'Lanzador de guerra',
    'Weapon Master': 'Maestro de armas',
    'Agent of Order': 'Agente del orden',
    'Baleful Scion': 'Vástago funesto',
    'Cohort of Chaos': 'Cohorte del caos',
    'Outlands Envoy': 'Enviado de las Tierras Exteriores',
    'Planar Wanderer': 'Vagabundo planar',
    'Righteous Heritor': 'Heredero justo',
    'Scion of the Outer Planes': 'Vástago de los planos exteriores',
    'Strixhaven Initiate': 'Iniciado de Strixhaven',
    'Strixhaven Mascot': 'Mascota de Strixhaven',
    'Adept of the Black Robes': 'Adepto de las Túnicas Negras',
    'Adept of the Red Robes': 'Adepto de las Túnicas Rojas',
    'Adept of the White Robes': 'Adepto de las Túnicas Blancas',
    'Divinely Favored': 'Favorecido por los dioses',
    'Initiate of High Sorcery': 'Iniciado de la Alta Hechicería',
    'Knight of the Crown': 'Caballero de la Corona',
    'Knight of the Rose': 'Caballero de la Rosa',
    'Knight of the Sword': 'Caballero de la Espada',
    'Squire of Solamnia': 'Escudero de Solamnia',
    'Bountiful Luck': 'Suerte abundante',
    'Dragon Fear': 'Miedo dracónico',
    'Dragon Hide': 'Piel de dragón',
    'Dwarven Fortitude': 'Fortaleza enana',
    'Drow High Magic': 'Alta magia drow',
    'Flames of Phlegethos': 'Llamas de Flegetos',
    'Infernal Constitution': 'Constitución infernal',
    'Orcish Fury': 'Furia orca',
    Prodigy: 'Prodigio',
    'Revenant Blade': 'Hoja del renacido',
    'Second Chance': 'Segunda oportunidad',
    'Squat Nimbleness': 'Agilidad compacta',
    'Svirfneblin Magic': 'Magia svirfneblin',
    'Wood Elf Magic': 'Magia de elfo de los bosques',
    'Elven Accuracy': 'Precisión élfica',
    'Fade Away': 'Desvanecerse',
    'Fey Teleportation': 'Teletransporte feérico',
  };

  const D = root.ClassData;
  if (!D || D.translatedEs) return;
  D.translatedEs = true;
  const feature = (f, parent) => {
    f.english = f.name;
    f.name = FEAT[f.name] || (parent && f.name === parent.english ? parent.name : f.name);
    if (Array.isArray(f.children)) f.children = f.children.map(c => FEAT[c] || c);
  };
  for (const c of Object.values(D.classes)) (c.features || []).forEach(f => feature(f));
  for (const s of D.subclasses) {
    s.english = s.name;
    s.name = SUB[s.id] || s.name;
    (s.features || []).forEach(f => feature(f, s));
  }
  for (const o of D.options || []) {
    o.english = o.name;
    o.name = OPT[o.name] || o.name;
  }
  if (root.Catalog)
    for (const f of root.Catalog.feats || []) {
      if (f.english) continue;
      f.english = f.name;
      f.name = FEATS[f.name] || f.name;
    }
  root.NamesEs = { choice: n => CHOICE[n] || n, feature: n => FEAT[n] || n };
})(typeof window !== 'undefined' ? window : globalThis);
